/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardLocationsRouteImport } from './routes/dashboard/locations'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard/insights'
import { Route as DashboardGeofencesRouteImport } from './routes/dashboard/geofences'
import { Route as DashboardFlagsRouteImport } from './routes/dashboard/flags'
import { Route as DashboardDrivesRouteImport } from './routes/dashboard/drives'
import { Route as DashboardChargingRouteImport } from './routes/dashboard/charging'
import { Route as DashboardBatteryRouteImport } from './routes/dashboard/battery'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardDrivesMapRouteImport } from './routes/dashboard/drives_.map'
import { Route as DashboardDrivesDriveIdRouteImport } from './routes/dashboard/drives_.$driveId'
import { Route as DashboardChargingMapRouteImport } from './routes/dashboard/charging_.map'
import { Route as DashboardChargingChargeIdRouteImport } from './routes/dashboard/charging_.$chargeId'
import { Route as ApiCronPollRouteImport } from './routes/api/cron/poll'
import { Route as ApiAuthTeslaLoginRouteImport } from './routes/api/auth/tesla/login'
import { Route as ApiAuthTeslaCallbackRouteImport } from './routes/api/auth/tesla/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocationsRoute = DashboardLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGeofencesRoute = DashboardGeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlagsRoute = DashboardFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDrivesRoute = DashboardDrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChargingRoute = DashboardChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBatteryRoute = DashboardBatteryRouteImport.update({
  id: '/battery',
  path: '/battery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDrivesMapRoute = DashboardDrivesMapRouteImport.update({
  id: '/drives_/map',
  path: '/drives/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDrivesDriveIdRoute = DashboardDrivesDriveIdRouteImport.update({
  id: '/drives_/$driveId',
  path: '/drives/$driveId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChargingMapRoute = DashboardChargingMapRouteImport.update({
  id: '/charging_/map',
  path: '/charging/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChargingChargeIdRoute =
  DashboardChargingChargeIdRouteImport.update({
    id: '/charging_/$chargeId',
    path: '/charging/$chargeId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiCronPollRoute = ApiCronPollRouteImport.update({
  id: '/api/cron/poll',
  path: '/api/cron/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTeslaLoginRoute = ApiAuthTeslaLoginRouteImport.update({
  id: '/api/auth/tesla/login',
  path: '/api/auth/tesla/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTeslaCallbackRoute = ApiAuthTeslaCallbackRouteImport.update({
  id: '/api/auth/tesla/callback',
  path: '/api/auth/tesla/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/battery': typeof DashboardBatteryRoute
  '/dashboard/charging': typeof DashboardChargingRoute
  '/dashboard/drives': typeof DashboardDrivesRoute
  '/dashboard/flags': typeof DashboardFlagsRoute
  '/dashboard/geofences': typeof DashboardGeofencesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cron/poll': typeof ApiCronPollRoute
  '/dashboard/charging/$chargeId': typeof DashboardChargingChargeIdRoute
  '/dashboard/charging/map': typeof DashboardChargingMapRoute
  '/dashboard/drives/$driveId': typeof DashboardDrivesDriveIdRoute
  '/dashboard/drives/map': typeof DashboardDrivesMapRoute
  '/api/auth/tesla/callback': typeof ApiAuthTeslaCallbackRoute
  '/api/auth/tesla/login': typeof ApiAuthTeslaLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/battery': typeof DashboardBatteryRoute
  '/dashboard/charging': typeof DashboardChargingRoute
  '/dashboard/drives': typeof DashboardDrivesRoute
  '/dashboard/flags': typeof DashboardFlagsRoute
  '/dashboard/geofences': typeof DashboardGeofencesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/cron/poll': typeof ApiCronPollRoute
  '/dashboard/charging/$chargeId': typeof DashboardChargingChargeIdRoute
  '/dashboard/charging/map': typeof DashboardChargingMapRoute
  '/dashboard/drives/$driveId': typeof DashboardDrivesDriveIdRoute
  '/dashboard/drives/map': typeof DashboardDrivesMapRoute
  '/api/auth/tesla/callback': typeof ApiAuthTeslaCallbackRoute
  '/api/auth/tesla/login': typeof ApiAuthTeslaLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/battery': typeof DashboardBatteryRoute
  '/dashboard/charging': typeof DashboardChargingRoute
  '/dashboard/drives': typeof DashboardDrivesRoute
  '/dashboard/flags': typeof DashboardFlagsRoute
  '/dashboard/geofences': typeof DashboardGeofencesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cron/poll': typeof ApiCronPollRoute
  '/dashboard/charging_/$chargeId': typeof DashboardChargingChargeIdRoute
  '/dashboard/charging_/map': typeof DashboardChargingMapRoute
  '/dashboard/drives_/$driveId': typeof DashboardDrivesDriveIdRoute
  '/dashboard/drives_/map': typeof DashboardDrivesMapRoute
  '/api/auth/tesla/callback': typeof ApiAuthTeslaCallbackRoute
  '/api/auth/tesla/login': typeof ApiAuthTeslaLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/battery'
    | '/dashboard/charging'
    | '/dashboard/drives'
    | '/dashboard/flags'
    | '/dashboard/geofences'
    | '/dashboard/insights'
    | '/dashboard/locations'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/cron/poll'
    | '/dashboard/charging/$chargeId'
    | '/dashboard/charging/map'
    | '/dashboard/drives/$driveId'
    | '/dashboard/drives/map'
    | '/api/auth/tesla/callback'
    | '/api/auth/tesla/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/battery'
    | '/dashboard/charging'
    | '/dashboard/drives'
    | '/dashboard/flags'
    | '/dashboard/geofences'
    | '/dashboard/insights'
    | '/dashboard/locations'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/cron/poll'
    | '/dashboard/charging/$chargeId'
    | '/dashboard/charging/map'
    | '/dashboard/drives/$driveId'
    | '/dashboard/drives/map'
    | '/api/auth/tesla/callback'
    | '/api/auth/tesla/login'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/battery'
    | '/dashboard/charging'
    | '/dashboard/drives'
    | '/dashboard/flags'
    | '/dashboard/geofences'
    | '/dashboard/insights'
    | '/dashboard/locations'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/cron/poll'
    | '/dashboard/charging_/$chargeId'
    | '/dashboard/charging_/map'
    | '/dashboard/drives_/$driveId'
    | '/dashboard/drives_/map'
    | '/api/auth/tesla/callback'
    | '/api/auth/tesla/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCronPollRoute: typeof ApiCronPollRoute
  ApiAuthTeslaCallbackRoute: typeof ApiAuthTeslaCallbackRoute
  ApiAuthTeslaLoginRoute: typeof ApiAuthTeslaLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/locations': {
      id: '/dashboard/locations'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof DashboardLocationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/geofences': {
      id: '/dashboard/geofences'
      path: '/geofences'
      fullPath: '/dashboard/geofences'
      preLoaderRoute: typeof DashboardGeofencesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flags': {
      id: '/dashboard/flags'
      path: '/flags'
      fullPath: '/dashboard/flags'
      preLoaderRoute: typeof DashboardFlagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drives': {
      id: '/dashboard/drives'
      path: '/drives'
      fullPath: '/dashboard/drives'
      preLoaderRoute: typeof DashboardDrivesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/charging': {
      id: '/dashboard/charging'
      path: '/charging'
      fullPath: '/dashboard/charging'
      preLoaderRoute: typeof DashboardChargingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/battery': {
      id: '/dashboard/battery'
      path: '/battery'
      fullPath: '/dashboard/battery'
      preLoaderRoute: typeof DashboardBatteryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drives_/map': {
      id: '/dashboard/drives_/map'
      path: '/drives/map'
      fullPath: '/dashboard/drives/map'
      preLoaderRoute: typeof DashboardDrivesMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drives_/$driveId': {
      id: '/dashboard/drives_/$driveId'
      path: '/drives/$driveId'
      fullPath: '/dashboard/drives/$driveId'
      preLoaderRoute: typeof DashboardDrivesDriveIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/charging_/map': {
      id: '/dashboard/charging_/map'
      path: '/charging/map'
      fullPath: '/dashboard/charging/map'
      preLoaderRoute: typeof DashboardChargingMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/charging_/$chargeId': {
      id: '/dashboard/charging_/$chargeId'
      path: '/charging/$chargeId'
      fullPath: '/dashboard/charging/$chargeId'
      preLoaderRoute: typeof DashboardChargingChargeIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/cron/poll': {
      id: '/api/cron/poll'
      path: '/api/cron/poll'
      fullPath: '/api/cron/poll'
      preLoaderRoute: typeof ApiCronPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/tesla/login': {
      id: '/api/auth/tesla/login'
      path: '/api/auth/tesla/login'
      fullPath: '/api/auth/tesla/login'
      preLoaderRoute: typeof ApiAuthTeslaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/tesla/callback': {
      id: '/api/auth/tesla/callback'
      path: '/api/auth/tesla/callback'
      fullPath: '/api/auth/tesla/callback'
      preLoaderRoute: typeof ApiAuthTeslaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBatteryRoute: typeof DashboardBatteryRoute
  DashboardChargingRoute: typeof DashboardChargingRoute
  DashboardDrivesRoute: typeof DashboardDrivesRoute
  DashboardFlagsRoute: typeof DashboardFlagsRoute
  DashboardGeofencesRoute: typeof DashboardGeofencesRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardLocationsRoute: typeof DashboardLocationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChargingChargeIdRoute: typeof DashboardChargingChargeIdRoute
  DashboardChargingMapRoute: typeof DashboardChargingMapRoute
  DashboardDrivesDriveIdRoute: typeof DashboardDrivesDriveIdRoute
  DashboardDrivesMapRoute: typeof DashboardDrivesMapRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBatteryRoute: DashboardBatteryRoute,
  DashboardChargingRoute: DashboardChargingRoute,
  DashboardDrivesRoute: DashboardDrivesRoute,
  DashboardFlagsRoute: DashboardFlagsRoute,
  DashboardGeofencesRoute: DashboardGeofencesRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardLocationsRoute: DashboardLocationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChargingChargeIdRoute: DashboardChargingChargeIdRoute,
  DashboardChargingMapRoute: DashboardChargingMapRoute,
  DashboardDrivesDriveIdRoute: DashboardDrivesDriveIdRoute,
  DashboardDrivesMapRoute: DashboardDrivesMapRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCronPollRoute: ApiCronPollRoute,
  ApiAuthTeslaCallbackRoute: ApiAuthTeslaCallbackRoute,
  ApiAuthTeslaLoginRoute: ApiAuthTeslaLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
